# // Copyright 2024 Paion Data. All rights reserved.
annotations:
  screwdriver.cd/chainPR: true

shared:
  image: buildpack-deps:22.04-scm

jobs:
  code-style:
    requires: [~pr, ~commit]
    steps:
      - install-node: sd-cmd exec paion-data/install-node@latest 18
      - install-yarn: npm install -g yarn
      - install-dependencies: yarn
      - run-prettier: yarn prettier . --check
      - run-eslint: yarn eslint .

  tests:
    requires: [code-style]
    steps:
      - install-node: sd-cmd exec paion-data/install-node@latest 18
      - install-yarn: npm install -g yarn
      - install-dependencies: yarn
      - run-unit-tests: yarn test

  e2e-tests:
    requires: [~pr, ~commit]
    steps:
      - install-node: sd-cmd exec paion-data/install-node@latest 18
      - install-yarn: npm install -g yarn
      - install-dependencies: |
          apt-get install libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libnss3 libxss1 libasound2 libxtst6 xauth xvfb -y
          yarn
      - load-env-file: mv .env.test .env
      - start-test-nlp-service: |
          yarn start:ai &
          yarn wait-on-ai
      - start-test-graph-api-service: |
          yarn start:graph-api &
          cd scripts
          timeout 1m bash -c 'until ./remove-graph.sh; do sleep 3; done'
          cd ../
      - run-e2e-in-dev-mode: |
          yarn start &
          yarn wait-on-dev
          yarn e2e
      - run-e2e-in-prod-mode: |
          yarn build
          npm install -g serve
          serve -s dist -l 3000 &
          yarn wait-on-prod
          yarn e2e
