# // Copyright 2024 Paion Data. All rights reserved.
annotations:
  screwdriver.cd/chainPR: false

shared:
  image: buildpack-deps:22.04-scm

jobs:
  main:
    requires: [~commit]
    template: paion-data/react-app-release-definition-template@latest
    parameters:
      ami-region:
        value: "us-west-1"
      ami-name:
        value: "nexusgraph"
      ami-build-instance-type:
        value: "t2.micro"
      aws-deploy-region:
        value: "us-west-1"
      aws-ec2-instance-type:
        value: "t2.small"
      instance-name:
        value: "Paion Data Nexus Graph"
      security-groups:
        value: "[\"Paion Data Nexus Graph\"]"
      domain:
        value: "nexusgraph.io"
      route-53-zone-id:
        value: "Z08521792247NCOO6R00S"
      node-version:
        value: "18"
      logto-app-id:
        value: "9pbqegk2jveej1maygwvj"
      logto-endpoint-url:
        value: "https://06n5lk.logto.app/"
      logto-api-resource-identifier:
        value: "https://api.nexusgraph.io"
    steps:
      - generate-dist: |
          echo NLP_CLIENT=TheresaClient                                                                 >> .env
          echo GRAPH_API_CLIENT=AstraiosGraphClient                                                     >> .env
          echo GRAPH_API_ENDPOINT=https://api.nexusgraph.io/graph                                       >> .env
          echo SKIP_SIGN_IN=false                                                                       >> .env
          echo LOGTO_APP_ID=$(meta get parameters.logto-app-id.value)                                   >> .env
          echo LOGTO_ENDPOINT_URL=$(meta get parameters.logto-endpoint-url.value)                       >> .env
          echo LOGTO_API_RESOURCE_IDENTIFIER=$(meta get parameters.logto-api-resource-identifier.value) >> .env
          echo LOGTO_SIGN_IN_CALLBACK_URL=https://$(meta get parameters.domain.value)/callback          >> .env
          echo LOGTO_SIGN_OUT_REDIRECT_URL=https://$(meta get parameters.domain.value)                  >> .env          
          yarn
          yarn build
